"""add description to the items table

Revision ID: 68256d922542
Revises: ec45b3ae5040
Create Date: 2026-08-27 09:30:09.569546

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '68256d922542'
down_revision = 'ec45b3ae5040'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('description', sa.String(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('items', schema=None) as batch_op:
        batch_op.drop_column('description')

    # ### end Alembic commands ###
